---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamlakant/spring-cloud-config
          searchPaths: demo-app
          deleteUntrackedBranches: true
server:
  port: 8888